version: '3.9'
services:
  bot:
    container_name: bot
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    networks:
      - backend

networks:
  backend:
    driver: bridge      
